apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello
  namespace: default
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: hello
  source:
    path: helm
    repoURL: https://github.com/tlee14-upstart/hello.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
