apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello
  namespace: default
spec:
  project: default
  source:
    path: helm
    repoURL: https://github.com/tlee14-upstart/hello.git
    targetRevision: HEAD
    helm:
      values: |
        image:
          tag: v1
        ingress:
          host: 10.130.2.126:5001
      version: v3
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
